/**
 * ai-parser.contract.ts — AI Output Parser Types (织梦机 v2 / W01)
 *
 * Defines the contract for parsing and validating structured AI output.
 * Supports strict validation, auto-repair, fallback extraction, and full failure modes.
 *
 * [v2.1.1-AI] Added ChapterPacket, WritingContract, TianDiRen output shapes.
 */

/**
 * Status of the parsing operation.
 */
export type ParserStatus = 'valid' | 'repaired' | 'fallback' | 'failed';

/**
 * Input for the structured parser pipeline.
 */
export interface ParseInput {
  rawContent: string;
  schema: string;
  strict: boolean;
}

/**
 * Output from the structured parser pipeline.
 */
export interface ParseOutput {
  data: Record<string, unknown>;
  validationErrors: string[];
  repairLog: string[];
  fallbackText?: string;
}

// ===== v2.1.1-AI: AI Output Shapes =====

/**
 * ChapterPacket output shape — generated by AI for chapter-by-chapter content.
 */
export interface ChapterPacketOutput {
  title: string;
  line: string;
  position: string;
  chapterFunction: string;
  layer1: string;
  layer2: string;
  layer3: string;
  layer4: string;
  status: string;
}

/**
 * WritingContract output shape — generated by AI from premise-to-contract mapping.
 */
export interface WritingContractOutput {
  narrativeDistance: string;
  expositionStrategy: string;
  taboos: string[];
  reasoning: string;
}

/**
 * TianDiRen output shape — Heaven/Earth/Human three-layer worldbuilding.
 */
export interface TianDiRenOutput {
  tian: string;
  di: string;
  ren: string;
}

/**
 * Discriminated union of all AI structured output shapes.
 */
export type AiStructuredOutput = ChapterPacketOutput | WritingContractOutput | TianDiRenOutput;

/**
 * JSON Schema for ChapterPacket output validation.
 */
export const CHAPTER_PACKET_SCHEMA = JSON.stringify({
  type: 'object',
  properties: {
    title: { type: 'string', default: '' },
    line: { type: 'string', default: '' },
    position: { type: 'string', default: '' },
    chapterFunction: { type: 'string', default: '' },
    layer1: { type: 'string', default: '' },
    layer2: { type: 'string', default: '' },
    layer3: { type: 'string', default: '' },
    layer4: { type: 'string', default: '' },
    status: { type: 'string', default: 'pending' },
  },
  required: ['title', 'line', 'position', 'chapterFunction'],
});

/**
 * JSON Schema for WritingContract output validation.
 */
export const WRITING_CONTRACT_SCHEMA = JSON.stringify({
  type: 'object',
  properties: {
    narrativeDistance: { type: 'string', default: 'medium' },
    expositionStrategy: { type: 'string', default: 'balanced' },
    taboos: { type: 'array', default: [] },
    reasoning: { type: 'string', default: '' },
  },
  required: ['narrativeDistance', 'expositionStrategy', 'taboos', 'reasoning'],
});

/**
 * JSON Schema for TianDiRen output validation.
 */
export const TIAN_DI_REN_SCHEMA = JSON.stringify({
  type: 'object',
  properties: {
    tian: { type: 'string', default: '' },
    di: { type: 'string', default: '' },
    ren: { type: 'string', default: '' },
  },
  required: ['tian', 'di', 'ren'],
});
